name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录阿里云镜像仓库（ACR）
      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login --username "${{ secrets.ACR_USERNAME }}" crpi-2n3ymsn0ffeo6dfn.cn-shanghai.personal.cr.aliyuncs.com --password-stdin

      # 构建并推送镜像
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.cn-your-region.aliyuncs.com/your-repo/photo-gallery .
          docker push registry.cn-your-region.aliyuncs.com/your-repo/photo-gallery

      # 配置 kubectl
      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # 部署到 Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
